export default function Hidden() {
    return (
        <div className="flex flex-col gap-3 text-[14px] text-left ">
            Hidden Dynamic Island ( отсутствует островок безопаности )
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis consectetur quas placeat veniam ipsam quis porro tempore voluptate. Modi, commodi unde quod tempore aliquam voluptatum vel ipsum natus neque doloremque.
        </div>
    )
}